# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 2) do

  create_table "comments", :force => true do |t|
    t.column "author",     :string
    t.column "title",      :string
    t.column "completed",  :integer
    t.column "body",       :text
    t.column "created_at", :datetime
  end

  create_table "photos", :force => true do |t|
    t.column "comment_id",   :integer
    t.column "content_type", :string
    t.column "filename",     :string
    t.column "size",         :integer
    t.column "parent_id",    :integer
    t.column "thumbnail",    :string
    t.column "width",        :integer
    t.column "height",       :integer
  end

end
